# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.17.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ENV["MATCH_KEYCHAIN_NAME"] = "ios-build.keychain"
    # ensure_git_status_clean 
    
  end

  desc "Create keychains to store certificates"
  lane :keychains do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end

  desc "Fetches provisioning profile and certificates from github repo"
  desc "Usage fastlane certificates export_method:\"enterprise\""
  lane :certificates do |options|
    export_method = options[:export_method]
    match(
      type: "development",
      app_identifier: ["org.sagebase.BridgeAppSDKSample", "org.sagebase.BridgeAppSDKSample.watchkitapp", "org.sagebase.BridgeAppSDKSample.watchkitapp.watchkitextension"],
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: true
    )
  end

  desc "Archive and export app"
  desc "Usage fastlane archive scheme:\"BridgeAppSDKSample\" export_method:\"enterprise\""
  lane :archive do |options|
    scheme = options[:scheme]
    export_method = options[:export_method]
    gym(
      scheme: "#{scheme}",
      clean: true,
      include_bitcode: true,
      output_directory: "./build",
      output_name: "#{scheme}.ipa",
      export_method: "#{export_method}",
      destination: "generic/platform=iOS",
    )
  end

  desc "This lane is for CI bots to archive and export"
  lane :ci_archive do |options|
    scheme = options[:scheme]
    export_method = options[:export_method]
    keychains
    certificates
    archive(scheme: "#{scheme}",export_method: "#{export_method}")
  end

  desc "Runs all the tests"
  lane :test do |options|
    if options[:scheme]
      scan(scheme: options[:scheme])
    else
      scan
    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "BridgeAppSDKSample") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "BridgeAppSDKSample") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
